version: "3.7"

services:

  gencross-online:
    image: gencross-online:${DOCKER_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

  db:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${HOST_MYSQL_DATA_DIR}:/var/lib/mysql
